version: '3'
services:
  redis:
    image: redis:alpine
    container_name: eog-rediscache
    ports:
      - "16379:6379"
  videoserver:
    build: videoserver/.
    image: ai2incubator/eog-videoserver:latest
    container_name: eog-videoserver
    ports:
      - "18080:8080"