version: '3'
services:
  redis:
    image: redis:alpine
    container_name: eog-rediscache
    ports:
      - "16379:6379"
  videoserver:
    build: videoserver/.
    image: ai2incubator/eog-videoserver:latest
    container_name: eog-videoserver
    ports:
      - "18080:8080"
    volumes:
      - "./videoserver:/opt/videoserver"
    command: python app.py --port 8080 --redis_host redis --redis_port 6379
  detector:
    build: detector/.
    image: ai2incubator/eog-detector:latest
    container_name: eog-detector
    volumes:
      - "./detector:/opt/detector"
    command: python3 loop.py --stream_url rtsp://172.16.20.108:554/11 --redis_host redis --redis_port 6379
