version: '3'
services:
  redis:
    image: redis:alpine
    container_name: eog-rediscache
    ports:
      - "16379:6379"
  videoserver:
    build: videoserver/.
    image: ai2incubator/eog-videoserver:latest
    container_name: eog-videoserver
    ports:
      - "18080:8080"
    command: python app.py --port 8080 --redis_host redis --redis_port 6379
  detector:
    build: detector/.
    image: ai2incubator/eog-detector:latest
    container_name: eog-detector
    command: python app.py --redis_host redis --redis_port 6379